#!/usr/bin/env bash
# installing and configure HAproxy on server.
sudo apt -y install haproxy
sudo tee -a /etc/haproxy/haproxy.cfg > /dev/null <<EOT
frontend http_web
    bind *:80
    default_backend rgw
backend rgw
    balance roundrobin
    server  rgw1 35.231.164.114:80 check
    server  rgw2 54.196.208.192:80 check
EOT
sudo service haproxy restart
